name: 'Create Neelix experience'
description: 'Creates a Neelix experience from the provided inputs'
author: Neelix.IO
branding:
  icon: message-square
  color: white
inputs:
  api-token:
    description: 'Neelix API token (should be stored as secret)'
    required: true
  consortium-id:
    description: 'ID of consortium experiences will belong to'
    required: true
  commentary:
    description: 'Sets `commentary` field of new experience.'
  weight:
    description: >
      'Sets `weight` field of new experience. Default used if value not '
      'provided.'
    default: '0'
  activity-id:
    description: >
      'ID of an activity belonging to same consortium as experience.'
      'Sets `activity_id` field of new experience. '
  category-ids:
    description: >
      'IDs of categoris belonging to same consortium as experience. Use '
      'comma-separated list for multiple values (e.g. "1,2,3"). Adds '
      'specified categories to new experience. '
  team-ids:
    description: >
      'IDs of teams belonging to same consortium as experience. Use '
      'comma-separated list for multiple values (e.g. "1,2,3"). Adds specified '
      'teams to new experience. '
  external-ref:
    description: >
      'External reference url. Sets value of `external_ref` on new experience.'
outputs:
  experience-id:
    description: 'ID of new experience'
runs:
  using: 'node16'
  main: 'dist/index.js'
